DROP VIEW IF EXISTS ADISCOURSEWORK.MAIN_VIEW cascade;
drop view if exists adiscoursework.deaths_reasons_influence_on_happiness cascade;

CREATE VIEW ADISCOURSEWORK.MAIN_VIEW AS
SELECT
       NAME COUNTRY_NAME,
       YEAR,
       GDP,
        --SOCIAL_SUPPORT,
       FREEDOM,
         --ENERGY_CONSUMPTION/(AVERAGE_POPULATION::REAL - (2020-YEAR) * C.NET_POPULATION_CHANGE) as ENERGY_CONSUMPTION_PER_CAPITA,
       TRUST,
         --GENEROSITY,
         --(TOTAL_DEATHS::REAL)/(AVERAGE_POPULATION::REAL - (2020-YEAR) * C.NET_POPULATION_CHANGE) AS DEATHS_PER_CAPITA,
         --AREA,
         --(AVERAGE_POPULATION::REAL - (2020-YEAR) * C.NET_POPULATION_CHANGE) / AREA AS POPULATION_DENSITY,
       HAPPINESS_SCORE,
       category
FROM ADISCOURSEWORK.HAPPINESS_REPORT
INNER JOIN ADISCOURSEWORK.DATE D ON D.ID = ADISCOURSEWORK.HAPPINESS_REPORT.DATE_ID
INNER JOIN ADISCOURSEWORK.COUNTRY C ON C.ID = ADISCOURSEWORK.HAPPINESS_REPORT.COUNTRY_ID
WHERE YEAR BETWEEN 2015 AND 2019;
/*
    1)дропнули life_expectancy - большая corr с gdp.
    2)дропнули energy_consumption_per_capita - большая corr с gdp
*/

-- \copy (SELECT * FROM adiscoursework.main_view) TO 'C:\Users\Asus\Desktop\Лабы2022\CursachDataAnalysis\main_view.csv' with csv header




--убрали исходя из данных corr() illnesses.py
----убрали исходя из обоюдной корреляции
--******************************************************************************************************
CREATE VIEW ADISCOURSEWORK.DEATHS_REASONS_INFLUENCE_ON_HAPPINESS AS
    SELECT C.NAME AS COUNTRY_NAME,
           YEAR,
           DR.NAME AS REASON_NAME,
           COUNT / (AVERAGE_POPULATION::REAL - (2020-YEAR) * NET_POPULATION_CHANGE) * 10000 AS COUNT
    FROM ADISCOURSEWORK.DEATH_REPORT
    INNER JOIN ADISCOURSEWORK.COUNTRY C ON C.ID = DEATH_REPORT.COUNTRY_ID
    INNER JOIN ADISCOURSEWORK.DATE D ON D.ID = DEATH_REPORT.DATE_ID
    INNER JOIN ADISCOURSEWORK.DEATH_REASON DR ON DR.ID = DEATH_REPORT.REASON_ID
    WHERE YEAR BETWEEN 2015 AND 2019 AND COUNT IS NOT NULL;